version: '3.7'

name: aggr-server

networks:
  backend:
    name: aggr_backend

x-common-collector: &common-collector
  image: aggr-server
  build:
    context: .
    dockerfile: ./docker/Dockerfile.dev
    args:
      - WORKDIR=${WORKDIR}
  volumes:
    - ./src:${WORKDIR}
    - ./data:${WORKDIR}/data
    - /usr/src/app/node_modules
  environment:
    - NODE_ENV=development
    - API_ROLE=false
    - COLLECT_ROLE=true
    - INFLUX_HOST=influx
    - INFLUX_PORT=8086
    - INFLUX_DATABASE=significant_trades
  env_file:
    - ./.env.dev
  networks:
    - backend
  restart: unless-stopped

services:
  api:
    container_name: aggr-api
    image: aggr-server
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ./src:${WORKDIR}
      - ./config/api/config.json:${WORKDIR}/config.json
      - ./data:${WORKDIR}/data
      - /usr/src/app/node_modules
    ports:
      - "${HOST_PORT:-3000}:${PORT}"
    environment:
      - NODE_ENV=development
      - API_ROLE=true
      - COLLECT_ROLE=false
      - INFLUX_HOST=influx
      - INFLUX_PORT=8086
      - INFLUX_DATABASE=significant_trades
    env_file:
      - ./.env.dev
    networks:
      - backend
    depends_on:
      influx:
        condition: service_healthy
    command: >
      /bin/sh -c "
        wait-for-it.sh influx:8086 --timeout=30 --strict -- 
        npm run dev"

  collector-btc:
    <<: *common-collector
    container_name: aggr-collector-btc
    volumes:
      - ./src:${WORKDIR}
      - ./config/collectors/btc.json:${WORKDIR}/config.json
      - ./data:${WORKDIR}/data
      - /usr/src/app/node_modules
    environment:
      - COLLECTOR_ID=btc-collector
      - PAIRS=COINBASE:BTC-USD,BINANCE:btcusdt
      - INFLUX_HOST=influx
    command: >
      /bin/sh -c "
        wait-for-it.sh influx:8086 --timeout=30 --strict -- 
        npm run dev"
    depends_on:
      influx:
        condition: service_healthy

  collector-eth:
    <<: *common-collector
    container_name: aggr-collector-eth
    volumes:
      - ./src:${WORKDIR}
      - ./config/collectors/eth.json:${WORKDIR}/config.json
      - ./data:${WORKDIR}/data
      - /usr/src/app/node_modules
    environment:
      - COLLECTOR_ID=eth-collector
      - PAIRS=COINBASE:ETH-USD,BINANCE:ethusdt
      - INFLUX_HOST=influx
    command: >
      /bin/sh -c "
        wait-for-it.sh influx:8086 --timeout=30 --strict -- 
        npm run dev"
    depends_on:
      influx:
        condition: service_healthy

  influx:
    container_name: aggr-influx
    image: influxdb:1.8.10
    ports:
      - "${HOST_INFLUX_PORT:-8086}:${INFLUX_PORT}"
    volumes:
      - influx_data:/var/lib/influxdb
    networks:
      - backend
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_DB=significant_trades
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
    healthcheck:
      test: ["CMD", "influx", "-execute", "SHOW DATABASES"]
      interval: 5s
      timeout: 1s
      retries: 5

  chronograf:
    container_name: aggr-chronograf
    image: chronograf:latest
    volumes:
      - chronograf_data:/var/lib/chronograf
      - ./config/chronograf/sources.json:/usr/share/chronograf/resources/sources/default.json
    ports:
      - "${HOST_CHRONOGRAF_PORT:-8885}:8888"
    depends_on:
      influx:
        condition: service_healthy
    environment:
      - INFLUXDB_URL=http://influx:8086
      - INFLUXDB_USERNAME=
      - INFLUXDB_PASSWORD=
      - INFLUXDB_ORG=
      - INFLUXDB_BUCKET=significant_trades
    networks:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8888"]
      interval: 5s
      timeout: 1s
      retries: 5

  telegraf:
    container_name: aggr-telegraf
    image: telegraf:latest
    volumes:
      - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - backend
    depends_on:
      influx:
        condition: service_healthy
    environment:
      - INFLUXDB_URL=http://influx:8086
      - INFLUXDB_DB=significant_trades

volumes:
  influx_data:
  chronograf_data: